# Connexion DB (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/vermeg_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root

spring.datasource.password=

# Hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< HEAD
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
=======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pfevermeg@gmail.com
spring.mail.password=teenjoagvxrwvmhk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
>>>>>>> 001547f950356ad1bb5e9b623a6a219b0aae7f00
